version: '3'
services:

  #PHP Service
  cookbook_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cookbook_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: cookbook_app
      SERVICE_TAGS: dev
      MYSQL_HOST: cookbook_db
      MYSQL_DATABASE: database
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  cookbook_webserver:
    image: nginx:alpine
    container_name: cookbook_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  cookbook_db:
    image: mysql:5.7.22
    container_name: cookbook_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local